language: node_js
install:
  - npm ci
  - npm install -g codecov
node_js:
  - node
services:
  - postgres
before_script:
  - psql -c 'create database tests;' -U postgres
script:
  - npm run test
  - codecov
