version: 1.0.{build}
environment:
  APP_PORT: 3333
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Password12!
  POSTGRES_DATABASE: gofinances
  DOCS_URL: https://github.com/DiegoVictor/gofinances-api#errors-reference
  NODE_ENV: test
build: off
services:
  - postgresql
install:
  - cmd: |
      SET PGUSER=postgres
      SET PGPASSWORD=Password12!
      PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
      createdb tests
  - cmd: npm ci
  - cmd: npm run typeorm migration:run
test_script:
  - cmd: npm run test
on_success:
  - cmd: |
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
      .\codecov.exe

