version: 1.0.{build}
environment:
  APP_PORT: 3333
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Password12!
  DOCS_URL: https://github.com/DiegoVictor/gofinances-api#errors-reference
  NODE_ENV: test
build: off
services:
  - postgresql13
install:
  - ps: npm ci
test_script:
  - cmd: |
      SET PGUSER=postgres
      SET PGPASSWORD=Password12!
      PATH=C:\Program Files\PostgreSQL\13\bin\;%PATH%
      createdb tests
  - cmd: npm run test
on_success:
  - ps: >-
      $ProgressPreference = 'SilentlyContinue'

      Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe

      .\codecov.exe

